[theme]
primaryColor = "#E9580C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6FA"
textColor = "#102B46"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
